spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://##############################################
    username: ##########
    #insert password
    password: ##########

  jpa:
    properties:
      hibernate:
        show-sql: "true"
        format_sql: "true"
    hibernate:
      ddl-auto: update
